encoding: UTF-8
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-coffeescript
    - jekyll-paginate
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
